//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReefKineticsEntities : DbContext
    {
        public ReefKineticsEntities()
            : base("name=ReefKineticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbModel> tbModels { get; set; }
        public virtual DbSet<tbRobot> tbRobots { get; set; }
        public virtual DbSet<tbRobotType> tbRobotTypes { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
